services:
  postgres:
    image: postgres:16-alpine
    container_name: eventos-db
    environment:
      POSTGRES_DB: eventos
      POSTGRES_USER: eventos
      POSTGRES_PASSWORD: eventos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: